#ifndef NATIVE_X_H
#define NATIVE_X_H

#include "image.h"
#include "../defines.h"

#ifdef UMF_USE_NATIVE

namespace umfnative
{
    
/**
 * Wrappers over the native functions generated by Halide
 */

UMF void convertToYCbCr(umf::ImageRGB *rgb, umf::ImageGray *yuv);

UMF void getChromeMaskYCbCr(umf::ImageGray* yuv, umf::ImageGray* mask, umf::ImageGray* map);

UMF void getChromeMaskNV21(umf::ImageGray* yuv, umf::ImageGray* mask, umf::ImageGray* map);

UMF void smooth3x3(umf::ImageGray *gray, umf::ImageGray *result);

UMF void computeGradients3x3(umf::ImageGray *input, umf::ImageFloat *gradX, umf::ImageFloat *gradY);


UMF void h_subsample2( unsigned char *img, int ncols, int nrows, unsigned char *img2);
UMF void h_subsample4( unsigned char *img, int ncols, int nrows, unsigned char *img2);

}

#endif

#endif // NATIVE_X_H
